# Generated by Django 6.0.2 on 2026-03-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
